### ISSUE TITLE
How to use with BaseActivity?

### ISSUE THREAD

**Issue by goodibunakov** [kirich1409/ViewBindingPropertyDelegate#42]
Or with BaseFragment

**Comment by goodibunakov** [comment]
Or BaseFragment

**Comment by kirich1409** [comment]
Please describe the issue

**Comment by goodibunakov** [comment]
I have to use BaseActivity in my project. 
I did: 
```
class SplashActivity : BaseActivity<SplashViewModel>() {
private val binding by viewBinding(ActivitySplashBinding::bind, R.id.container) 
}
```

And received: 
Unable to start activity ComponentInfo{.presentation.activity.SplashActivity}: java.lang.NullPointerException: activity.findViewById(viewBindingRootId) must not be null

**Comment by kirich1409** [comment]
You need to set content view before access to the viewbinding delegate

**Comment by goodibunakov** [comment]
```
class BuyIdeaEnterAmountActivity : BaseActivity() {

    private val binding by viewBinding(ActivityBuyIdeaEnterAmountBinding::bind, R.id.root)

    override fun getLayoutView() = binding.root

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
}

public abstract class BaseActivity extends AppCompatActivity{
 @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(getLayoutView());        
    }

     protected View getLayoutView() {
            return null;
        }
}
```

I get
```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saprun.septem.dev/com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity}: java.lang.IllegalArgumentException: ID does not reference a View inside this Activity
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: ID does not reference a View inside this Activity
        at android.app.Activity.requireViewById(Activity.java:3231)
        at androidx.core.app.ActivityCompat.requireViewById(ActivityCompat.java:363)
        at com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity$$special$$inlined$viewBindingActivity$1.invoke(ActivityViewBindings.kt:65)
        at com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity$$special$$inlined$viewBindingActivity$1.invoke(Unknown Source:2)
        at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:59)
        at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:46)
        at com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity.getBinding(Unknown Source:7)
        at com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity.getLayoutView(BuyIdeaEnterAmountActivity.kt:39)
        at com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity.getLayoutView(BuyIdeaEnterAmountActivity.kt:30)
        at com.saprun.septem.activity.BaseActivity.onCreate(BaseActivity.java:50)
        at com.saprun.septem.createOperation.view.buy.BuyIdeaEnterAmountActivity.onCreate(BuyIdeaEnterAmountActivity.kt:42)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
```

What is wrong?
