### ISSUE TITLE
ViewBinding stopped working with proguarded builds

### ISSUE THREAD

**Issue by cristan** [kirich1409/ViewBindingPropertyDelegate#49]
When I run a release build I get the following exception:
```
Caused by: java.lang.NoSuchMethodException: com.action.consumerapp.databinding.ActivitySplashBinding.bind [class android.view.View]
   at java.lang.Class.getMethod(Class.java:2072)
   at java.lang.Class.getMethod(Class.java:1693)
   at d.a.a.j.a.<init>(ViewBindingCache.kt:97)
   at d.a.a.j.f.a(ViewBindingCache.kt:27)
   at d.a.a.g$a.a(ActivityViewBindings.kt:38)
   at d.a.a.g$a.invoke(Unknown Source:2)
   at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.f(ViewBindingProperty.kt:59)
   at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.a(ViewBindingProperty.kt:46)
   at com.action.consumerapp.feature.splash.SplashActivity.i(Unknown Source:7)
```

This occurs at 'com.github.kirich1409:viewbindingpropertydelegate:1.4.3' and 'com.github.kirich1409:viewbindingpropertydelegate:1.4.4'. This doesn't happen with  'com.github.kirich1409:viewbindingpropertydelegate:1.4.2' (or 'com.kirich1409.viewbindingpropertydelegate:viewbindingpropertydelegate:1.4.2').

**Comment by kirich1409** [comment]
Check version 1.4.5

**Comment by alexkopenkov** [comment]
I had a similar problem (v1.4.4) and in version 1.4.5 everything works well.

**Comment by sandip-torinit** [comment]
Getting same issue in 1.5.8.

**Comment by kirich1409** [comment]
> Getting same issue in 1.5.8.

Show me the stacktrace and the code with usage of ViewBinding in that place

**Comment by kirich1409** [comment]
I've just found out the problem. Will be fixed in next release. As temporary solution please add to you ProGuard config next lines
```
-keep,allowoptimization class * implements androidx.viewbinding.ViewBinding {
    public static *** bind(android.view.View);
    public static *** inflate(...);
}
```

**Comment by sandip-torinit** [comment]
> -keep,allowoptimization class * implements androidx.viewbinding.ViewBinding {
>     public static *** bind(android.view.View);
>     public static *** inflate(...);
> }

This worked. Thanks

**Comment by al-t** [comment]
There is a similar crash in 1.5.9 as well:

```
Caused by: java.lang.NoSuchMethodException: my.project.databinding.MiisFragmentShowcaseBinding.bind [class android.view.View]
	at java.lang.Class.getMethod(Class.java:2103)
	at java.lang.Class.getMethod(Class.java:1724)
	at by.kirich1409.viewbindingdelegate.internal.BindViewBinding.<init>(ViewBindingCache.kt:14)
	at by.kirich1409.viewbindingdelegate.ReflectionFragmentViewBindings$viewBinding$3.invoke(FragmentViewBindings.kt:28)
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:8)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:3)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at my.project.ShowcaseFragment.getBinding(ShowcaseFragment.kt:8)
	...
```
	
Adding the proguard rules helps:	
```
-keep,allowoptimization class * implements androidx.viewbinding.ViewBinding {
    public static *** bind(android.view.View);
    public static *** inflate(...);
}
```
